### ISSUE TITLE
Rails 7, Sorcery, Effective 

### ISSUE THREAD

**Issue by Nerian** [code-and-effect/effective_resources#14]
Hi,

I am trying to update to Rails 7 my app but I keep hitting the same issue:

```
➜  sample_app git:(main)  rails c
/Users/Nerian/.rvm/rubies/ruby-2.7.4/lib/ruby/2.7.0/net/protocol.rb:66: warning: already initialized constant Net::ProtocRetryError
/Users/Nerian/.rvm/gems/ruby-2.7.4/gems/net-protocol-0.1.3/lib/net/protocol.rb:68: warning: previous definition of ProtocRetryError was here
/Users/Nerian/.rvm/rubies/ruby-2.7.4/lib/ruby/2.7.0/net/protocol.rb:206: warning: already initialized constant Net::BufferedIO::BUFSIZE
/Users/Nerian/.rvm/gems/ruby-2.7.4/gems/net-protocol-0.1.3/lib/net/protocol.rb:208: warning: previous definition of BUFSIZE was here
/Users/Nerian/.rvm/rubies/ruby-2.7.4/lib/ruby/2.7.0/net/protocol.rb:503: warning: already initialized constant Net::NetPrivate::Socket
/Users/Nerian/.rvm/gems/ruby-2.7.4/gems/net-protocol-0.1.3/lib/net/protocol.rb:504: warning: previous definition of Socket was here
Traceback (most recent call last):
	39: from bin/rails:4:in `<main>'
	38: from /Users/Nerian/.rvm/gems/ruby-2.7.4/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	37: from /Users/Nerian/.rvm/gems/ruby-2.7.4/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	36: from /Users/Nerian/.rvm/gems/ruby-2.7.4/gems/railties-7.0.2.3/lib/rails/commands.rb:18:in `<main>'
	35: from /Users/Nerian/.rvm/gems/ruby-2.7.4/gems/railties-7.0.2.3/lib/rails/command.rb:48:in `invoke'
	34: from /Users/Nerian/.rvm/gems/ruby-2.7.4/gems/railties-7.0.2.3/lib/rails/command/base.rb:87:in `perform'
	33: from /Users/Nerian/.rvm/gems/ruby-2.7.4/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	32: from /Users/Nerian/.rvm/gems/ruby-2.7.4/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	31: from /Users/Nerian/.rvm/gems/ruby-2.7.4/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	30: from /Users/Nerian/.rvm/gems/ruby-2.7.4/gems/railties-7.0.2.3/lib/rails/commands/console/console_command.rb:101:in `perform'
	29: from /Users/Nerian/.rvm/gems/ruby-2.7.4/gems/railties-7.0.2.3/lib/rails/command/actions.rb:15:in `require_application_and_environment!'
	28: from /Users/Nerian/.rvm/gems/ruby-2.7.4/gems/railties-7.0.2.3/lib/rails/command/actions.rb:28:in `require_environment!'
	27: from /Users/Nerian/.rvm/gems/ruby-2.7.4/gems/railties-7.0.2.3/lib/rails/application.rb:348:in `require_environment!'
	26: from /Users/Nerian/.rvm/gems/ruby-2.7.4/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
	25: from /Users/Nerian/.rvm/gems/ruby-2.7.4/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	24: from /Users/Nerian/.rvm/gems/ruby-2.7.4/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	23: from /private/tmp/sample_app/config/environment.rb:5:in `<main>'
	22: from /Users/Nerian/.rvm/gems/ruby-2.7.4/gems/railties-7.0.2.3/lib/rails/application.rb:372:in `initialize!'
	21: from /Users/Nerian/.rvm/gems/ruby-2.7.4/gems/railties-7.0.2.3/lib/rails/initializable.rb:60:in `run_initializers'
	20: from /Users/Nerian/.rvm/rubies/ruby-2.7.4/lib/ruby/2.7.0/tsort.rb:205:in `tsort_each'
	19: from /Users/Nerian/.rvm/rubies/ruby-2.7.4/lib/ruby/2.7.0/tsort.rb:226:in `tsort_each'
	18: from /Users/Nerian/.rvm/rubies/ruby-2.7.4/lib/ruby/2.7.0/tsort.rb:347:in `each_strongly_connected_component'
	17: from /Users/Nerian/.rvm/rubies/ruby-2.7.4/lib/ruby/2.7.0/tsort.rb:347:in `call'
	16: from /Users/Nerian/.rvm/rubies/ruby-2.7.4/lib/ruby/2.7.0/tsort.rb:347:in `each'
	15: from /Users/Nerian/.rvm/rubies/ruby-2.7.4/lib/ruby/2.7.0/tsort.rb:349:in `block in each_strongly_connected_component'
	14: from /Users/Nerian/.rvm/rubies/ruby-2.7.4/lib/ruby/2.7.0/tsort.rb:431:in `each_strongly_connected_component_from'
	13: from /Users/Nerian/.rvm/rubies/ruby-2.7.4/lib/ruby/2.7.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	12: from /Users/Nerian/.rvm/rubies/ruby-2.7.4/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each'
	11: from /Users/Nerian/.rvm/gems/ruby-2.7.4/gems/railties-7.0.2.3/lib/rails/initializable.rb:61:in `block in run_initializers'
	10: from /Users/Nerian/.rvm/gems/ruby-2.7.4/gems/railties-7.0.2.3/lib/rails/initializable.rb:32:in `run'
	 9: from /Users/Nerian/.rvm/gems/ruby-2.7.4/gems/railties-7.0.2.3/lib/rails/initializable.rb:32:in `instance_exec'
	 8: from /Users/Nerian/.rvm/gems/ruby-2.7.4/gems/effective_resources-1.17.0/lib/effective_resources/engine.rb:24:in `block in <class:Engine>'
	 7: from /Users/Nerian/.rvm/gems/ruby-2.7.4/gems/activesupport-7.0.2.3/lib/active_support/lazy_load_hooks.rb:42:in `on_load'
	 6: from /Users/Nerian/.rvm/gems/ruby-2.7.4/gems/activesupport-7.0.2.3/lib/active_support/lazy_load_hooks.rb:42:in `each'
	 5: from /Users/Nerian/.rvm/gems/ruby-2.7.4/gems/activesupport-7.0.2.3/lib/active_support/lazy_load_hooks.rb:43:in `block in on_load'
	 4: from /Users/Nerian/.rvm/gems/ruby-2.7.4/gems/activesupport-7.0.2.3/lib/active_support/lazy_load_hooks.rb:66:in `execute_hook'
	 3: from /Users/Nerian/.rvm/gems/ruby-2.7.4/gems/activesupport-7.0.2.3/lib/active_support/lazy_load_hooks.rb:61:in `with_execution_control'
	 2: from /Users/Nerian/.rvm/gems/ruby-2.7.4/gems/activesupport-7.0.2.3/lib/active_support/lazy_load_hooks.rb:71:in `block in execute_hook'
	 1: from /Users/Nerian/.rvm/gems/ruby-2.7.4/gems/activesupport-7.0.2.3/lib/active_support/lazy_load_hooks.rb:71:in `class_eval'
/Users/Nerian/.rvm/gems/ruby-2.7.4/gems/effective_resources-1.17.0/lib/effective_resources/engine.rb:25:in `block (2 levels) in <class:Engine>': uninitialized constant EffectiveResources::Engine::ActsAsArchived (NameError)
```

I tracked this down to using both sorcery and effective_resources.

This is a base Rails straight from the generator, just adding gem 'sorcery', and gem 'effective_resources': 

https://github.com/Nerian/example_sorcery_effective

Doing a `rails console` gives me that error:

I am not sure what could be going on. I tried going through the code for both projects but I don't see anything weird. Any ideas?

Thanks!

**Comment by matt-riemer** [comment]
Upgrade to effectie_resources 1.17.1

I wrapped everything in a config.to_prepare and it seems to do the trick!

https://github.com/code-and-effect/effective_resources/commit/c164d58197d3769ce45a42dfff3c84206add8d58

**Comment by Nerian** [comment]
Niice! That did the trick. Now EffectiveResources does load. I added now effective datatables gem but it has an error. 

Perhaps we need to apply the same kind of change?

https://github.com/Nerian/example_sorcery_effective/commit/e62022b6ea0294229a483ccd9830f0cfb602f4d1

```
➜  sample_app git:(main)  rails c
/Users/Nerian/.rvm/gems/ruby-3.1.1/gems/effective_datatables-4.10.7/lib/effective_datatables/engine.rb:10:in `block (2 levels) in <class:Engine>': uninitialized constant EffectiveDatatables::Engine::EffectiveDatatablesHelper (NameError)

        helper EffectiveDatatablesHelper
               ^^^^^^^^^^^^^^^^^^^^^^^^^
	from /Users/Nerian/.rvm/gems/ruby-3.1.1/gems/activesupport-7.0.2.3/lib/active_support/lazy_load_hooks.rb:71:in `class_eval'
	from /Users/Nerian/.rvm/gems/ruby-3.1.1/gems/activesupport-7.0.2.3/lib/active_support/lazy_load_hooks.rb:71:in `block in execute_hook'
	from /Users/Nerian/.rvm/gems/ruby-3.1.1/gems/activesupport-7.0.2.3/lib/active_support/lazy_load_hooks.rb:61:in `with_execution_control'
	from /Users/Nerian/.rvm/gems/ruby-3.1.1/gems/activesupport-7.0.2.3/lib/active_support/lazy_load_hooks.rb:66:in `execute_hook'
	from /Users/Nerian/.rvm/gems/ruby-3.1.1/gems/activesupport-7.0.2.3/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
	from /Users/Nerian/.rvm/gems/ruby-3.1.1/gems/activesupport-7.0.2.3/lib/active_support/lazy_load_hooks.rb:51:in `each'
	from /Users/Nerian/.rvm/gems/ruby-3.1.1/gems/activesupport-7.0.2.3/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
	from /Users/Nerian/.rvm/gems/ruby-3.1.1/gems/actionpack-7.0.2.3/lib/action_controller/base.rb:270:in `<class:Base>'
	from /Users/Nerian/.rvm/gems/ruby-3.1.1/gems/actionpack-7.0.2.3/lib/action_controller/base.rb:166:in `<module:ActionController>'
	from /Users/Nerian/.rvm/gems/ruby-3.1.1/gems/actionpack-7.0.2.3/lib/action_controller/base.rb:7:in `<main>'
	from /Users/Nerian/.rvm/gems/ruby-3.1.1/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/Nerian/.rvm/gems/ruby-3.1.1/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/Nerian/.rvm/gems/ruby-3.1.1/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
	from /Users/Nerian/.rvm/gems/ruby-3.1.1/gems/actionpack-7.0.2.3/lib/action_controller/railtie.rb:81:in `block (3 levels) in <class:Railtie>'
	from /Users/Nerian/.rvm/gems/ruby-3.1.1/gems/actionpack-7.0.2.3/lib/action_controller/railtie.rb:77:in `each'
	from /Users/Nerian/.rvm/gems/ruby-3.1.1/gems/actionpack-7.0.2.3/lib/action_controller/railtie.rb:77:in `block (2 levels) in <class:Railtie>'
	from /Users/Nerian/.rvm/gems/ruby-3.1.1/gems/activesupport-7.0.2.3/lib/active_support/lazy_load_hooks.rb:71:in `class_eval'
	from /Users/Nerian/.rvm/gems/ruby-3.1.1/gems/activesupport-7.0.2.3/lib/active_support/lazy_load_hooks.rb:71:in `block in execute_hook'
	from /Users/Nerian/.rvm/gems/ruby-3.1.1/gems/activesupport-7.0.2.3/lib/active_support/lazy_load_hooks.rb:61:in `with_execution_control'
	from /Users/Nerian/.rvm/gems/ruby-3.1.1/gems/activesupport-7.0.2.3/lib/active_support/lazy_load_hooks.rb:66:in `execute_hook'
	from /Users/Nerian/.rvm/gems/ruby-3.1.1/gems/activesupport-7.0.2.3/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
	from /Users/Nerian/.rvm/gems/ruby-3.1.1/gems/activesupport-7.0.2.3/lib/active_support/lazy_load_hooks.rb:51:in `each'
	from /Users/Nerian/.rvm/gems/ruby-3.1.1/gems/activesupport-7.0.2.3/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
	from /Users/Nerian/.rvm/gems/ruby-3.1.1/gems/actionpack-7.0.2.3/lib/action_controller/api.rb:148:in `<class:API>'
	from /Users/Nerian/.rvm/gems/ruby-3.1.1/gems/actionpack-7.0.2.3/lib/action_controller/api.rb:89:in `<module:ActionController>'
	from /Users/Nerian/.rvm/gems/ruby-3.1.1/gems/actionpack-7.0.2.3/lib/action_controller/api.rb:7:in `<main>'
	from /Users/Nerian/.rvm/gems/ruby-3.1.1/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/Nerian/.rvm/gems/ruby-3.1.1/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/Nerian/.rvm/gems/ruby-3.1.1/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
	from /Users/Nerian/.rvm/gems/ruby-3.1.1/gems/sorcery-0.16.3/lib/sorcery/engine.rb:16:in `block in <class:Engine>'
	from /Users/Nerian/.rvm/gems/ruby-3.1.1/gems/railties-7.0.2.3/lib/rails/initializable.rb:32:in `instance_exec'
	from /Users/Nerian/.rvm/gems/ruby-3.1.1/gems/railties-7.0.2.3/lib/rails/initializable.rb:32:in `run'
	from /Users/Nerian/.rvm/gems/ruby-3.1.1/gems/railties-7.0.2.3/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /Users/Nerian/.rvm/rubies/ruby-3.1.1/lib/ruby/3.1.0/tsort.rb:228:in `block in tsort_each'
	from /Users/Nerian/.rvm/rubies/ruby-3.1.1/lib/ruby/3.1.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/Nerian/.rvm/rubies/ruby-3.1.1/lib/ruby/3.1.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/Nerian/.rvm/rubies/ruby-3.1.1/lib/ruby/3.1.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/Nerian/.rvm/rubies/ruby-3.1.1/lib/ruby/3.1.0/tsort.rb:347:in `each'
	from /Users/Nerian/.rvm/rubies/ruby-3.1.1/lib/ruby/3.1.0/tsort.rb:347:in `call'
	from /Users/Nerian/.rvm/rubies/ruby-3.1.1/lib/ruby/3.1.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/Nerian/.rvm/rubies/ruby-3.1.1/lib/ruby/3.1.0/tsort.rb:226:in `tsort_each'
	from /Users/Nerian/.rvm/rubies/ruby-3.1.1/lib/ruby/3.1.0/tsort.rb:205:in `tsort_each'
	from /Users/Nerian/.rvm/gems/ruby-3.1.1/gems/railties-7.0.2.3/lib/rails/initializable.rb:60:in `run_initializers'
	from /Users/Nerian/.rvm/gems/ruby-3.1.1/gems/railties-7.0.2.3/lib/rails/application.rb:372:in `initialize!'
	from /private/tmp/sample_app/config/environment.rb:5:in `<main>'
	from /Users/Nerian/.rvm/gems/ruby-3.1.1/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/Nerian/.rvm/gems/ruby-3.1.1/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/Nerian/.rvm/gems/ruby-3.1.1/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
	from /Users/Nerian/.rvm/gems/ruby-3.1.1/gems/railties-7.0.2.3/lib/rails/application.rb:348:in `require_environment!'
	from /Users/Nerian/.rvm/gems/ruby-3.1.1/gems/railties-7.0.2.3/lib/rails/command/actions.rb:28:in `require_environment!'
	from /Users/Nerian/.rvm/gems/ruby-3.1.1/gems/railties-7.0.2.3/lib/rails/command/actions.rb:15:in `require_application_and_environment!'
	from /Users/Nerian/.rvm/gems/ruby-3.1.1/gems/railties-7.0.2.3/lib/rails/commands/console/console_command.rb:101:in `perform'
	from /Users/Nerian/.rvm/gems/ruby-3.1.1/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /Users/Nerian/.rvm/gems/ruby-3.1.1/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/Nerian/.rvm/gems/ruby-3.1.1/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /Users/Nerian/.rvm/gems/ruby-3.1.1/gems/railties-7.0.2.3/lib/rails/command/base.rb:87:in `perform'
	from /Users/Nerian/.rvm/gems/ruby-3.1.1/gems/railties-7.0.2.3/lib/rails/command.rb:48:in `invoke'
	from /Users/Nerian/.rvm/gems/ruby-3.1.1/gems/railties-7.0.2.3/lib/rails/commands.rb:18:in `<main>'
	from /Users/Nerian/.rvm/gems/ruby-3.1.1/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/Nerian/.rvm/gems/ruby-3.1.1/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from bin/rails:4:in `<main>'
```

**Comment by danajanssen** [comment]
are we sure this is an effective gems problem? does this error still happen when you don't install sorcery? a quick review of sorcery looks like it has it's own submodule loading for it's plugins, and maybe that's the real source of the problem? we haven't run into this error on our own apps.

(we don't use sorcery and can't promise gems we maintain will play nice with it)

**Comment by matt-riemer** [comment]
Give effective_datatables 4.11.0 a shot.

I wrapped that ActiveSupport.on_load in a to_prepare, same fix as resources.

https://github.com/code-and-effect/effective_datatables/commit/f96f9031b5c7154e340bf2efb90f0763ad5df94d

Thanks Nerian!

**Comment by Nerian** [comment]
Working like a charm 🥳 Thanks!
